[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_AGIOS_DIONYSIOS_1", "Agios Dionysios A", 5000, ""],
	["TERRITORY_AGIOS_DIONYSIOS_F_1", "", 0, ""],
	["TERRITORY_AGIOS_DIONYSIOS_2", "Agios Dionysios B", 5000, ""],
	["TERRITORY_AGIOS_DIONYSIOS_F_2", "", 0, ""],
	["TERRITORY_AGIOS_DIONYSIOS_3", "Agios Dionysios C", 5000, ""],
	["TERRITORY_AGIOS_DIONYSIOS_F_3", "", 0, ""],
	["TERRITORY_VIKOS_1", "Vikos A", 5000, ""],
	["TERRITORY_VIKOS_F_1", "", 0, ""],
	["TERRITORY_VIKOS_2", "Vikos B", 5000, ""],
	["TERRITORY_VIKOS_F_2", "", 0, ""],
	["TERRITORY_VIKOS_3", "Vikos C", 5000, ""],
	["TERRITORY_VIKOS_F_3", "", 0, ""],
	["TERRITORY_PAROS_1", "Paros A", 5000, ""],
	["TERRITORY_PAROS_F_1", "", 0, ""],
	["TERRITORY_PAROS_2", "Paros B", 5000, ""],
	["TERRITORY_PAROS_F_2", "", 0, ""],
	["TERRITORY_PAROS_3", "Paros C", 5000, ""],
	["TERRITORY_PAROS_F_3", "", 0, ""]
]