[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_NEOCHORI_1", "Neochori A", 5000, ""],
	["TERRITORY_NEOCHORI_F_1", "", 0, ""],
	["TERRITORY_NEOCHORI_2", "Neochori B", 5000, ""],
	["TERRITORY_NEOCHORI_F_2", "", 0, ""],
	["TERRITORY_NEOCHORI_3", "Neochori C", 5000, ""],
	["TERRITORY_NEOCHORI_F_3", "", 0, ""],
	["TERRITORY_KORE_1", "Kore A", 5000, ""],
	["TERRITORY_KORE_F_1", "", 0, ""],
	["TERRITORY_KORE_2", "Kore B", 5000, ""],
	["TERRITORY_KORE_F_2", "", 0, ""],
	["TERRITORY_KORE_3", "Kore C", 5000, ""],
	["TERRITORY_KORE_F_3", "", 0, ""],
	["TERRITORY_ANTHRAKIA_1", "Anthrakia A", 5000, ""],
	["TERRITORY_ANTHRAKIA_F_1", "", 0, ""],
	["TERRITORY_ANTHRAKIA_2", "Anthrakia B", 5000, ""],
	["TERRITORY_ANTHRAKIA_F_2", "", 0, ""],
	["TERRITORY_ANTHRAKIA_3", "Anthrakia C", 5000, ""],
	["TERRITORY_ANTHRAKIA_F_3", "", 0, ""]
]