[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_OREOKASTRO_1", "Oreokastro A", 5000, ""],
	["TERRITORY_OREOKASTRO_F_1", "", 0, ""],
	["TERRITORY_OREOKASTRO_2", "Oreokastro B", 5000, ""],
	["TERRITORY_OREOKASTRO_F_2", "", 0, ""],
	["TERRITORY_OREOKASTRO_3", "Oreokastro C", 5000, ""],
	["TERRITORY_OREOKASTRO_F_3", "", 0, ""],
	["TERRITORY_ZAROS_1", "Zaros A", 5000, ""],
	["TERRITORY_ZAROS_F_1", "", 0, ""],
	["TERRITORY_ZAROS_2", "Zaros B", 5000, ""],
	["TERRITORY_ZAROS_F_2", "", 0, ""],
	["TERRITORY_ZAROS_3", "Zaros C", 5000, ""],
	["TERRITORY_ZAROS_F_3", "", 0, ""],
	["TERRITORY_SELAKANO_1", "Selakano A", 5000, ""],
	["TERRITORY_SELAKANO_F_1", "", 0, ""],
	["TERRITORY_SELAKANO_2", "Selakano B", 5000, ""],
	["TERRITORY_SELAKANO_F_2", "", 0, ""],
	["TERRITORY_SELAKANO_3", "Selakano C", 5000, ""],
	["TERRITORY_SELAKANO_F_3", "", 0, ""]
]