[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_THESIA_1", "Thesia A", 5000, ""],
	["TERRITORY_THESIA_F_1", "", 0, ""],
	["TERRITORY_THESIA_2", "Thesia B", 5000, ""],
	["TERRITORY_THESIA_F_2", "", 0, ""],
	["TERRITORY_THESIA_3", "Thesia C", 5000, ""],
	["TERRITORY_THESIA_F_3", "", 0, ""],
	["TERRITORY_FRINI_1", "Frini A", 5000, ""],
	["TERRITORY_FRINI_F_1", "", 0, ""],
	["TERRITORY_FRINI_2", "Frini B", 5000, ""],
	["TERRITORY_FRINI_F_2", "", 0, ""],
	["TERRITORY_FRINI_3", "Frini C", 5000, ""],
	["TERRITORY_FRINI_F_3", "", 0, ""],
	["TERRITORY_NERI_1", "Neri A", 5000, ""],
	["TERRITORY_NERI_F_1", "", 0, ""],
	["TERRITORY_NERI_2", "Neri B", 5000, ""],
	["TERRITORY_NERI_F_2", "", 0, ""],
	["TERRITORY_NERI_3", "Neri C", 5000, ""],
	["TERRITORY_NERI_F_3", "", 0, ""]
]