[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_PYRGOS_1", "Pyrgos A", 5000, ""],
	["TERRITORY_PYRGOS_F_1", "", 0, ""],
	["TERRITORY_PYRGOS_2", "Pyrgos B", 5000, ""],
	["TERRITORY_PYRGOS_F_2", "", 0, ""],
	["TERRITORY_PYRGOS_3", "Pyrgos C", 5000, ""],
	["TERRITORY_PYRGOS_F_3", "", 0, ""],
	["TERRITORY_TELOS_1", "Telos A", 5000, ""],
	["TERRITORY_TELOS_F_1", "", 0, ""],
	["TERRITORY_TELOS_2", "Telos B", 5000, ""],
	["TERRITORY_TELOS_F_2", "", 0, ""],
	["TERRITORY_TELOS_3", "Telos C", 5000, ""],
	["TERRITORY_TELOS_F_3", "", 0, ""],
	["TERRITORY_NEGADES_1", "Negades A", 5000, ""],
	["TERRITORY_NEGADES_F_1", "", 0, ""],
	["TERRITORY_NEGADES_2", "Negades B", 5000, ""],
	["TERRITORY_NEGADES_F_2", "", 0, ""],
	["TERRITORY_NEGADES_3", "Negades C", 5000, ""],
	["TERRITORY_NEGADES_F_3", "", 0, ""]
]