[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_LAKKA_1", "Lakka A", 5000, ""],
	["TERRITORY_LAKKA_F_1", "", 0, ""],
	["TERRITORY_LAKKA_2", "Lakka B", 5000, ""],
	["TERRITORY_LAKKA_F_2", "", 0, ""],
	["TERRITORY_LAKKA_3", "Lakka C", 5000, ""],
	["TERRITORY_LAKKA_F_3", "", 0, ""],
	["TERRITORY_KALOCHORI_1", "Kalochori A", 5000, ""],
	["TERRITORY_KALOCHORI_F_1", "", 0, ""],
	["TERRITORY_KALOCHORI_2", "Kalochori B", 5000, ""],
	["TERRITORY_KALOCHORI_F_2", "", 0, ""],
	["TERRITORY_KALOCHORI_3", "Kalochori C", 5000, ""],
	["TERRITORY_KALOCHORI_F_3", "", 0, ""],
	["TERRITORY_PANOCHORI_1", "Panochori A", 5000, ""],
	["TERRITORY_PANOCHORI_F_1", "", 0, ""],
	["TERRITORY_PANOCHORI_2", "Panochori B", 5000, ""],
	["TERRITORY_PANOCHORI_F_2", "", 0, ""],
	["TERRITORY_PANOCHORI_3", "Panochori C", 5000, ""],
	["TERRITORY_PANOCHORI_F_3", "", 0, ""]
]