[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_AGGELOCHORI_1", "Aggelochori A", 5000, ""],
	["TERRITORY_AGGELOCHORI_F_1", "", 0, ""],
	["TERRITORY_AGGELOCHORI_2", "Aggelochori B", 5000, ""],
	["TERRITORY_AGGELOCHORI_F_2", "", 0, ""],
	["TERRITORY_AGGELOCHORI_3", "Aggelochori C", 5000, ""],
	["TERRITORY_AGGELOCHORI_F_3", "", 0, ""],
	["TERRITORY_ABDERA_1", "Abdera A", 5000, ""],
	["TERRITORY_ABDERA_F_1", "", 0, ""],
	["TERRITORY_ABDERA_2", "Abdera B", 5000, ""],
	["TERRITORY_ABDERA_F_2", "", 0, ""],
	["TERRITORY_ABDERA_3", "Abdera C", 5000, ""],
	["TERRITORY_ABDERA_F_3", "", 0, ""],
	["TERRITORY_CHARKIA_1", "Charkia A", 5000, ""],
	["TERRITORY_CHARKIA_F_1", "", 0, ""],
	["TERRITORY_CHARKIA_2", "Charkia B", 5000, ""],
	["TERRITORY_CHARKIA_F_2", "", 0, ""],
	["TERRITORY_CHARKIA_3", "Charkia C", 5000, ""],
	["TERRITORY_CHARKIA_F_3", "", 0, ""]
]