[
	["TERRITORY_AIRBASE_1", "Airbase A", 5000, ""],
	["TERRITORY_AIRBASE_F_1", "", 0, ""],
	["TERRITORY_AIRBASE_2", "Airbase B", 5000, ""],
	["TERRITORY_AIRBASE_F_2", "", 0, ""],
	["TERRITORY_AIRBASE_3", "Airbase C", 5000, ""],
	["TERRITORY_AIRBASE_F_3", "", 0, ""],
	["TERRITORY_KAVALA_1", "Kavala A", 5000, ""],
	["TERRITORY_KAVALA_F_1", "", 0, ""],
	["TERRITORY_KAVALA_2", "Kavala B", 5000, ""],
	["TERRITORY_KAVALA_F_2", "", 0, ""],
	["TERRITORY_KAVALA_3", "Kavala C", 5000, ""],
	["TERRITORY_KAVALA_F_3", "", 0, ""],
	["TERRITORY_ATHIRA_1", "Athira A", 5000, ""],
	["TERRITORY_ATHIRA_F_1", "", 0, ""],
	["TERRITORY_ATHIRA_2", "Athira B", 5000, ""],
	["TERRITORY_ATHIRA_F_2", "", 0, ""],
	["TERRITORY_ATHIRA_3", "Athira C", 5000, ""],
	["TERRITORY_ATHIRA_F_3", "", 0, ""],
	["TERRITORY_SOFIA_1", "Sofia A", 5000, ""],
	["TERRITORY_SOFIA_F_1", "", 0, ""],
	["TERRITORY_SOFIA_2", "Sofia B", 5000, ""],
	["TERRITORY_SOFIA_F_2", "", 0, ""],
	["TERRITORY_SOFIA_3", "Sofia C", 5000, ""],
	["TERRITORY_SOFIA_F_3", "", 0, ""]
]